SistemaCableInternet/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WebApplicationSistemaCableInternet.Interface;
using WebApplicationSistemaCableInternet.Models;

namespace WebApplicationSistemaCableInternet.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IServicioCliente servicio;
        public ClienteController(IServicioCliente servicio)
        {
            this.servicio = servicio;
        }
        public IActionResult Index(string mensaje = "", bool ocurrioError = false)
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                this.ViewData["Clase"] = "success";
                this.ViewData["Mensaje"] = mensaje;
                
                if (ocurrioError)
                {
                    this.ViewData["Clase"] = "danger";
                }
            }

            List<Cliente> listaClientes = this.servicio.ConsultarClientes();
            return this.View(listaClientes);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Crear(Cliente cliente)
        {
            string mensaje = "Ocurrio un error al intentar registrar el cliente, intente mas tarde.";
            bool ocurrioError = true;

            if (this.servicio.CrearCliente(cliente))
            {
                mensaje = "Cliente registrado exitosamente.";
                ocurrioError = false;
            }

            return RedirectToAction("Index", new { mensaje = mensaje, ocurrioError = ocurrioError});
        }

        public IActionResult Eliminar(int idCliente)
        {
            string mensaje = "Ocurrio un error al intentar eliminar el cliente, intente mas tarde.";
            bool ocurrioError = true;

            if (this.servicio.EliminarCliente(idCliente))
            {
                mensaje = "Cliente eliminado exitosamente.";
                ocurrioError = false;
            }

            return RedirectToAction("Index", new { mensaje = mensaje, ocurrioError = ocurrioError });
        }
    }
}

SistemaCableInternet/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WebApplicationSistemaCableInternet.Interface;
using WebApplicationSistemaCableInternet.Models;

namespace WebApplicationSistemaCableInternet.Controllers
{
    public class FacturaController : Controller
    {
        private readonly IServicioFactura servicio;
        private readonly IServicioCliente servicioClientes;
        private readonly IServiceServicio servicioPlanes;
        public FacturaController(IServicioFactura servicio,
            IServicioCliente servicioClientes, IServiceServicio servicioPlanes)
        {
            this.servicio = servicio;
            this.servicioClientes = servicioClientes;
            this.servicioPlanes = servicioPlanes;
        }
        public IActionResult Index(string mensaje = "", bool ocurrioError = false)
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                this.ViewData["Clase"] = "success";
                this.ViewData["Mensaje"] = mensaje;

                if (ocurrioError)
                {
                    this.ViewData["Clase"] = "danger";
                }
            }

            List<Factura> lista = this.servicio.ConsultarListado();
            return this.View(lista);
        }


        public IActionResult Detalle(int facturaId)
        {
            var model = new Factura();
            // Obtener datos de la factura
            model = this.servicio.ConsultarFactura(facturaId);

            return this.View(model);
        }

        public IActionResult Crear(int clienteId)
        {
            var model = new Factura();
            // Obtener la información del cliente
            var cliente = this.servicioClientes.ConsultarCliente(clienteId);
            if (cliente == null)
            {
                return RedirectToAction("Index", new { mensaje = "Error al consultar la información", ocurrioError = true });
            }
            model.Cliente = cliente;

            // Obtener los servicios del cliente
            model.Servicios = this.servicioPlanes.ConsultarServiciosCliente(clienteId);
            foreach (var servicio in model.Servicios)
            {
                servicio.Pagos = this.servicio.ConsultarMesesPago(clienteId, servicio.ServicioId);
            }

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Crear(Factura factura, int[] servicios, string[] detalles)
        {
            string mensaje = "Ocurrio un error al intentar guardar el registro, intente mas tarde.";
            bool ocurrioError = true;

            factura.Servicios = this.servicioPlanes.ConsultarServiciosCliente(factura.ClienteId);
            factura.DetallesFactura = new List<DetalleFactura>();
            var total = 0.0M;
            var descuento = 0.0M;

            // Calcular Total de la factura
            var totalPagosServicio = 0;
            foreach (var detalle in detalles)
            {
                var datos = detalle.Split('-');
                var servicio = factura.Servicios.Find(x => x.ServicioId.ToString() == datos[0]);
                totalPagosServicio += 1;

                factura.DetallesFactura.Add(new DetalleFactura()
                {
                    ServicioId = servicio.ServicioId,
                    Monto = servicio.Costo,
                    Descuento = servicio.Descuento,
                    FacturaId = factura.FacturaId,
                    MesId = int.Parse(datos[1])
                }
                ); ;
                total += (servicio.Costo - servicio.Descuento);
                descuento += servicio.Descuento; 
            }


            factura.Total = total;
            factura.Descuento = descuento;

            // Si hay mas de dos servicios aplicar descuento del 10%
            if (servicios.Length > 1)
            {
                decimal desc = (factura.Total * 10 / 100);
                factura.Total -= desc;
                factura.Descuento += desc;
            }

            // Si el servicio que esta pagando tiene mas de 6 pagos no cobrarle un mes
            foreach (var detalle in factura.Servicios)
            {
                if (factura.DetallesFactura.FindAll(x => x.ServicioId == detalle.ServicioId).Count >= 6)
                {
                    factura.Total -= factura.DetallesFactura[5].Monto - factura.DetallesFactura[5].Descuento;
                    factura.Descuento += factura.DetallesFactura[5].Monto - factura.DetallesFactura[5].Descuento;
                    factura.DetallesFactura[5].Monto = 0.0M;
                    factura.DetallesFactura[5].Descuento = 0.0M;
                }
            }

            if (this.servicio.CrearFactura(factura).FacturaId > 0)
            {
                mensaje = "registrado exitosamente.";
                ocurrioError = false;
            }

            return RedirectToAction("Index", new { mensaje = mensaje, ocurrioError = ocurrioError });
        }

    }
}

SistemaCableInternet/Controllers/PlanServicioController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WebApplicationSistemaCableInternet.Interface;
using WebApplicationSistemaCableInternet.Models;

namespace WebApplicationSistemaCableInternet.Controllers
{
    public class PlanServicioController : Controller
    {
        private readonly IServicioPlanServicio servicio;
        public PlanServicioController(IServicioPlanServicio servicio)
        {
            this.servicio = servicio;
        }
        public IActionResult Index(string mensaje = "", bool ocurrioError = false)
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                this.ViewData["Clase"] = "success";
                this.ViewData["Mensaje"] = mensaje;

                if (ocurrioError)
                {
                    this.ViewData["Clase"] = "danger";
                }
            }


            List<PlanServicio> listaClientes = this.servicio.ConsultarListadoPlanServicio();
            return this.View(listaClientes);
        }

        public IActionResult Crear()
        {
            return this.View();
        }

        // GET: PlanServicioController/Edit/5
        public IActionResult Editar(int id)
        {
            var model = this.servicio.ConsultarPlanServicio(id);

            return View(model);
        }

        // POST: PlanServicioController/Edit/5
        [HttpPost]
        public IActionResult Editar(int id, PlanServicio planServicio)
        {
            try
            {
                string mensaje = "Ocurrio un error al intentar registrar el cliente, intente mas tarde.";
                bool ocurrioError = true;
                planServicio.PlanServicioId = id;

                if (this.servicio.ActualizarPlanServicio(planServicio))
                {
                    mensaje = "Registrado exitosamente.";
                    ocurrioError = false;
                }
                return RedirectToAction("Index", new { mensaje = mensaje, ocurrioError = ocurrioError });
            }
            catch
            {
                return View();
            }
        }

    }
}

SistemaCableInternet/Controllers/ServicioController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WebApplicationSistemaCableInternet.Interface;
using WebApplicationSistemaCableInternet.Models;

namespace WebApplicationSistemaCableInternet.Controllers
{
    public class ServicioController : Controller
    {
        private readonly IServiceServicio servicio;
        private readonly IServicioCliente servicioClientes;
        private readonly IServicioPlanServicio servicioPlanes;
        public ServicioController(IServiceServicio servicio, 
            IServicioCliente servicioClientes, IServicioPlanServicio servicioPlanes)
        {
            this.servicio = servicio;
            this.servicioClientes = servicioClientes;
            this.servicioPlanes = servicioPlanes;
        }
        public IActionResult Index(string mensaje = "", bool ocurrioError = false)
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                this.ViewData["Clase"] = "success";
                this.ViewData["Mensaje"] = mensaje;

                if (ocurrioError)
                {
                    this.ViewData["Clase"] = "danger";
                }
            }

            List<Servicio> lista = this.servicio.ConsultarListado();
            return this.View(lista);
        }

        public IActionResult Crear()
        {
            var model = new Servicio();
            model.PlanesServicios = this.servicioPlanes.ConsultarListadoPlanServicio();
            model.Clientes = this.servicioClientes.ConsultarClientes();

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Crear(Servicio servicio)
        {
            string mensaje = "Ocurrio un error al intentar guardar el registro, intente mas tarde.";
            bool ocurrioError = true;

            if (this.servicio.RegistrarServicio(servicio))
            {
                mensaje = "registrado exitosamente.";
                ocurrioError = false;
            }

            return RedirectToAction("Index", new { mensaje = mensaje, ocurrioError = ocurrioError });
        }


        public IActionResult Editar(int id)
        {
            var model = this.servicio.ConsultarServicio(id);

            return View(model);
        }

        [HttpPost]
        public IActionResult Editar(int id, Servicio servicio)
        {
            try
            {
                string mensaje = "Ocurrio un error al intentar actualizar el registro, intente mas tarde.";
                bool ocurrioError = true;

                if (this.servicio.ActualizarServicio(servicio))
                {
                    mensaje = "Actualizado exitosamente.";
                    ocurrioError = false;
                }
                return RedirectToAction("Index", new { mensaje = mensaje, ocurrioError = ocurrioError });
            }
            catch
            {
                return View();
            }
        }

    }
}

SistemaCableInternet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/styles.css" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Prueba Jumay</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="/">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>

                        <div class="sb-sidenav-menu-heading">Catalogos</div>
                        <a class="nav-link" asp-area="" asp-controller="Servicio" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Servicios
                        </a>

                        <a class="nav-link" asp-area="" asp-controller="Cliente" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Clientes
                        </a>

                        <a class="nav-link" asp-area="" asp-controller="PlanServicio" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-cloud-plus"></i></div>
                            Planes
                        </a>

                        <div class="sb-sidenav-menu-heading">Facturas</div>

                        <a class="nav-link" asp-area="" asp-controller="Factura" >
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Listado
                        </a>

                        <a class="nav-link" asp-area="" asp-controller="Factura" asp-action="Crear">
                            <div class="sb-nav-link-icon"><i class="fas fa-plus"></i></div>
                            Nuevo
                        </a>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small"></div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-5">
                    @RenderBody()
                </div>
            </main>

        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>